name: "java test"
on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  junit:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 18

      - name: checkout
        uses: actions/checkout@v3

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: test
        run: ./gradlew test
